/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AppLoading: typeof import('./../components/AppLoading.vue')['default']
    MagicRings: typeof import('./../components/MagicRings.vue')['default']
    PasswordDialog: typeof import('./../components/PasswordDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionDialog: typeof import('./../components/SessionDialog.vue')['default']
    SessionSidebar: typeof import('./../components/SessionSidebar.vue')['default']
    TerminalWorkspace: typeof import('./../components/TerminalWorkspace.vue')['default']
  }
}
